modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[4,)" #mandatory (28 is current forge version)
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Lyrellion/Ars-Elemancy/issues" #optional

license="GNU Lesser General Public License v3.0"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="ars_elemancy" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Ars Elemancy" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/ars-elemancy" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile = "ars_elemancy_logo.png" #optional
# A text field displayed in the mod UI
credits = "Thanks to the Ars Nouveau team" #optional
# A text field displayed in the mod UI
authors = "Lyrellion" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''
This Ars Nouveau add-on expands on Ars Elemental, adding new dual- and quad- elemental gear.
'''
[[mixins]]
config="ars_elemancy.mixins.json"
[[dependencies.ars_elemancy]]
modId = "minecraft"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ars_elemancy]]
modId = "ars_nouveau"
versionRange = "[1.21.1-5.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ars_elemancy]]
modId = "ars_elemental"
versionRange = "[0.7.0.8,)"
ordering = "AFTER"
side = "BOTH"


